contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #impute channel"
    url: https://nfcore.slack.com/channels/impute
    about: Discussion about the nf-core/impute pipeline
